local resource_autoplace = require("resource-autoplace")

local PLANET = "ferrum"
local GROUND = PLANET .. "-plating"
local CLIFF_CONTROL = PLANET .. "_cliff"
local CLIFF = "cliff-" .. PLANET
-- Generated by tools/generate_cliffs.py; shadow sheets stay vanilla.
local CLIFF_SOURCE = "^__space%-age__/graphics/terrain/cliffs/fulgora/cliff%-fulgora%-"
local CLIFF_TARGET = "__planet-ferrum__/graphics/terrain/cliffs/cliff-" .. PLANET .. "-"

local SOLIDS = {
  { name = PLANET .. "-frame-ore", item = "flying-robot-frame", map_color = { 0.45, 0.50, 0.85 }, tint = { 0.4, 0.4, 0.5 }, base_density = 8, sheet = "frame-ore" },
  { name = PLANET .. "-gear-ore",  item = "iron-gear-wheel",    map_color = { 0.85, 0.85, 0.90 }, tint = { 0.8, 0.8, 0.85 }, base_density = 10, sheet = "gear-ore" },
  { name = PLANET .. "-clay-ore",  item = "ferrum-clay",        map_color = { 1.00, 0.85, 0.30 }, tint = { 1, 0.9, 0.5 }, base_density = 5, base = "stone" }
}
local LUBRICANT = PLANET .. "-lubricant"
local LUBRICANT_TINT = { 0.4, 1, 0.4 }

local DEBRIS = {
  ["fulgoran-ruin-tiny"] = 0.05
}
-- Corpse prototypes turned into decoratives, using fulgoran-ruin-tiny as the template.
local REMNANTS = {
  ["inserter-remnants"] = 0.01,
  ["bulk-inserter-remnants"] = 0.005,
  ["logistic-robot-remnants"] = 0.01,
  ["construction-robot-remnants"] = 0.01,
  ["assembling-machine-2-remnants"] = 0.002,
  ["assembling-machine-3-remnants"] = 0.002,
  ["roboport-remnants"] = 0.001
}
local SPRITE_FIELDS = { "filename", "width", "height", "size", "x", "y", "shift", "scale", "tint", "priority", "draw_as_shadow" }

for _, spec in pairs(SOLIDS) do resource_autoplace.initialize_patch_set(spec.name, true, PLANET) end
resource_autoplace.initialize_patch_set(LUBRICANT, true, PLANET)

local ground = table.deepcopy(data.raw.tile["refined-concrete"])
ground.name = GROUND
ground.minable = nil
ground.mined_sound = nil
ground.layer_group = "ground-natural"
ground.layer = 5
ground.autoplace = { probability_expression = "1" }

local cliff = table.deepcopy(data.raw.cliff["cliff-fulgora"])
cliff.name = CLIFF
cliff.map_color = { 0.80, 0.45, 0.25 }
for _, orientation in pairs(cliff.orientations) do
  for _, key in pairs({ "pictures", "pictures_lower" }) do
    for _, variation in pairs(orientation[key] or {}) do
      for _, layer in pairs(variation.layers or { variation }) do
        if not layer.draw_as_shadow then layer.filename = (layer.filename:gsub(CLIFF_SOURCE, CLIFF_TARGET)) end
      end
    end
  end
end

data:extend({
  ground,
  cliff,
  {
    type = "noise-expression",
    name = PLANET .. "_elevation",
    expression = "200 + 60 * quick_multioctave_noise{x = x, y = y, seed0 = map_seed, seed1 = 9001,\z
                  input_scale = 1/256, output_scale = 1, octaves = 4,\z
                  octave_output_scale_multiplier = 0.5, octave_input_scale_multiplier = 2}"
  },
  { type = "autoplace-control", name = CLIFF_CONTROL, localised_name = { "", "[entity=" .. CLIFF .. "] ", { "entity-name." .. CLIFF } }, order = "c-z", category = "cliff" }
})


local map_gen_settings = {
  property_expression_names = {
    elevation = PLANET .. "_elevation",
    cliffiness = "cliffiness_basic",
    cliff_elevation = "cliff_elevation_from_elevation"
  },
  cliff_settings = {
    name = CLIFF,
    control = CLIFF_CONTROL,
    cliff_elevation_0 = 10,
    cliff_elevation_interval = 15,
    richness = 1
  },
  autoplace_controls = { [CLIFF_CONTROL] = {} },
  autoplace_settings = {
    tile = { settings = { [GROUND] = {} } },
    decorative = { settings = {} },
    entity = { settings = {} }
  }
}

local function scatter(decorative, density)
  decorative.autoplace.probability_expression = density .. " * clamp(2 * basis_noise{x = x, y = y, seed0 = map_seed, seed1 = 777, input_scale = 1/40, output_scale = 1}, 0, 1)"
  data:extend({ decorative })
  map_gen_settings.autoplace_settings.decorative.settings[decorative.name] = {}
end

for source, density in pairs(DEBRIS) do
  local decorative = table.deepcopy(data.raw["optimized-decorative"][source])
  decorative.name = PLANET .. "-" .. source
  scatter(decorative, density)
end

for source, density in pairs(REMNANTS) do
  local remnant = data.raw.corpse[source]
  local variations = (remnant.animation.filename or remnant.animation.layers) and { remnant.animation } or remnant.animation
  local pictures = {}
  for _, variation in pairs(variations) do
    local picture = { layers = {} }
    for _, layer in pairs(variation.layers or { variation }) do
      local sprite = {}
      for _, field in pairs(SPRITE_FIELDS) do sprite[field] = table.deepcopy(layer[field]) end
      table.insert(picture.layers, sprite)
    end
    table.insert(pictures, picture)
  end
  local decorative = table.deepcopy(data.raw["optimized-decorative"]["fulgoran-ruin-tiny"])
  decorative.name = PLANET .. "-" .. source
  decorative.pictures = pictures
  decorative.collision_box = table.deepcopy(remnant.selection_box)
  scatter(decorative, density)
end

for i, spec in pairs(SOLIDS) do
  local item = data.raw.item[spec.item]
  local ore = table.deepcopy(data.raw.resource[spec.base or "iron-ore"])
  ore.name = spec.name
  ore.icon = item.icon
  ore.icon_size = item.icon_size
  ore.icons = item.icons
  ore.minable.result = spec.item
  ore.minable.results = nil
  ore.map_color = spec.map_color
  if spec.sheet then
    -- Generated by tools/generate_veins.py.
    ore.stages.sheet = {
      filename = "__planet-ferrum__/graphics/entity/" .. spec.sheet .. ".png",
      priority = "extra-high",
      size = 128,
      frame_count = 8,
      variation_count = 8,
      scale = 0.5
    }
  else
    ore.stages.sheet.tint = spec.tint
  end
  ore.factoriopedia_simulation = nil
  ore.autoplace = resource_autoplace.resource_autoplace_settings {
    name = spec.name,
    order = "b",
    base_density = spec.base_density,
    has_starting_area_placement = true,
    autoplace_set_name = PLANET,
    regular_rq_factor_multiplier = 1.1,
    starting_rq_factor_multiplier = 1.5,
    candidate_spot_count = 22
  }
  data:extend({
    ore,
    {
      type = "autoplace-control",
      name = spec.name,
      localised_name = { "", "[entity=" .. spec.name .. "] ", { "entity-name." .. spec.name } },
      richness = true,
      order = "b-" .. i,
      category = "resource"
    }
  })
  map_gen_settings.autoplace_controls[spec.name] = {}
  map_gen_settings.autoplace_settings.entity.settings[spec.name] = {}
end

local fluid = data.raw.fluid["lubricant"]
local well = table.deepcopy(data.raw.resource["crude-oil"])
well.name = LUBRICANT
well.created_effect = nil
well.icon = fluid.icon
well.icon_size = fluid.icon_size
well.icons = fluid.icons
well.minable.results = { { type = "fluid", name = "lubricant", amount = 10 } }
well.map_color = { 0.40, 1.00, 0.40 }
for _, layer in pairs(well.stages.sheet.layers or { well.stages.sheet }) do layer.tint = LUBRICANT_TINT end
well.factoriopedia_simulation = nil
well.autoplace = resource_autoplace.resource_autoplace_settings {
  name = LUBRICANT,
  order = "c",
  base_density = 15,
  base_spots_per_km2 = 1.8,
  random_probability = 1 / 48,
  random_spot_size_minimum = 1,
  random_spot_size_maximum = 1,
  additional_richness = 220000,
  has_starting_area_placement = true,
  autoplace_set_name = PLANET,
  regular_rq_factor_multiplier = 1
}
data:extend({
  well,
  {
    type = "autoplace-control",
    name = LUBRICANT,
    localised_name = { "", "[entity=" .. LUBRICANT .. "] ", { "entity-name." .. LUBRICANT } },
    richness = true,
    order = "b-9",
    category = "resource"
  }
})
map_gen_settings.autoplace_controls[LUBRICANT] = {}
map_gen_settings.autoplace_settings.entity.settings[LUBRICANT] = {}

return map_gen_settings